# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('query', models.CharField(blank=True, max_length=4096, verbose_name='Query')),
                ('creationdate', models.DateTimeField(auto_now_add=True, help_text='Creation Date', null=True, verbose_name='Date')),
                ('is_public', models.BooleanField(default=False, help_text='Is Public default True', verbose_name='Is Public')),
            ],
        ),
    ]
