# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='tablename',
            field=models.CharField(blank=True, max_length=128, verbose_name='Table Name'),
        ),
    ]
