# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0002_userquery_tablename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='Query',
        ),
    ]
